"""empty message

Revision ID: a9d33ee9a010
Revises: 12a03eeb5edf
Create Date: 2018-04-20 17:24:42.677175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d33ee9a010'
down_revision = '12a03eeb5edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_constraint('songs_artist_fkey', 'songs', type_='foreignkey')
    op.create_foreign_key(None, 'songs', 'artist', ['artist_id'], ['id'])
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.create_foreign_key('songs_artist_fkey', 'songs', 'artist', ['artist'], ['id'])
    op.drop_column('songs', 'artist_id')
    # ### end Alembic commands ###
